const PageConst = {
  no: "No.",
  weight: "Weightage (%)",
  weights: "Weightage",
  name: "Name",
  des: "Designation",
  dept: "Department",
  com: "Company",
  per: "Period",
  kra: "KRA",
  kraType: "KRA Type",
  kpi: "KPI",
  date: "Date",
  tmPr: "Time Period",
  empCode: "Employee Code",
  empName: "Name",
  score: "Score (0-5)",
  scores: "Score",
  scEr: "Score Eraned",
  per: "Period",
  goal: "Goal",
  type: " Type",
  sco1: "Employee1",
  sco2: "Employee2",
  finScor: "Final Score",
  doc: "Document",
  email: "Email",
  mob: "Mobile No.",
  he: "Hierarchy",
};
export { PageConst };
